apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: robi
    password: robimunawir
    database: currency_db
    isDefault: true
    jsonData:
      sslmode: disable
      postgresVersion: 1200
      timescaledb: false
